export const FETCH_IMAGES_START = 'FETCH_IMAGES_START';
export const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
export const FETCH_IMAGES_FAILURE = 'FETCH_IMAGES_FAILURE';

export const FETCH_IMAGE_BY_ID_START = 'FETCH_IMAGE_BY_ID_START';
export const FETCH_IMAGE_BY_ID_SUCCESS = 'FETCH_IMAGE_BY_ID_SUCCESS';
export const FETCH_IMAGE_BY_ID_FAILURE = 'FETCH_IMAGE_BY_ID_FAILURE';

export const CLEAR_IMAGE = 'CLEAR_IMAGE';
